# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.__version__

'1.19.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1

a=np.random.random((2,3,5))

In [8]:
# Method 2

a1=np.random.random((3,5))
a2=np.random.random((3,5))
a=np.array([a1,a2])

In [ ]:
# Method 3


#### 4. Print *a*.


In [10]:
# your code here
print(a)

[[[0.67828832 0.30768576 0.09465794 0.91100142 0.88879985]
  [0.07932956 0.3137879  0.32289145 0.4079848  0.45982861]
  [0.67746761 0.397713   0.73167579 0.59264927 0.06479876]]

 [[0.87643591 0.15762544 0.08580714 0.91867596 0.41774475]
  [0.31157827 0.84888892 0.56376389 0.62227452 0.60198114]
  [0.83276231 0.65303645 0.11482237 0.98667223 0.06543309]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [13]:
# your code here

b=np.ones((5,2,3))

#### 6. Print *b*.


In [14]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [19]:
# your code here
if a.size==b.size:
    print('Yes they do have the same size')
else:
    print("No they dont have the same size")

Yes they do have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


your answer here
No because they don't have the same shape

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [24]:
# your code here
c=np.transpose(b,(1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [27]:
# your code/answer here
d=np.add(a,c)

# It works because they have the same shape 

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [30]:
# your code/answer here
print('a:',a)
print('d:',d)

# Each value has a difference of exactly 1

a: [[[0.67828832 0.30768576 0.09465794 0.91100142 0.88879985]
  [0.07932956 0.3137879  0.32289145 0.4079848  0.45982861]
  [0.67746761 0.397713   0.73167579 0.59264927 0.06479876]]

 [[0.87643591 0.15762544 0.08580714 0.91867596 0.41774475]
  [0.31157827 0.84888892 0.56376389 0.62227452 0.60198114]
  [0.83276231 0.65303645 0.11482237 0.98667223 0.06543309]]]
d: [[[1.67828832 1.30768576 1.09465794 1.91100142 1.88879985]
  [1.07932956 1.3137879  1.32289145 1.4079848  1.45982861]
  [1.67746761 1.397713   1.73167579 1.59264927 1.06479876]]

 [[1.87643591 1.15762544 1.08580714 1.91867596 1.41774475]
  [1.31157827 1.84888892 1.56376389 1.62227452 1.60198114]
  [1.83276231 1.65303645 1.11482237 1.98667223 1.06543309]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [33]:
# your code here

e=np.multiply(a,c)
e

array([[[0.67828832, 0.30768576, 0.09465794, 0.91100142, 0.88879985],
        [0.07932956, 0.3137879 , 0.32289145, 0.4079848 , 0.45982861],
        [0.67746761, 0.397713  , 0.73167579, 0.59264927, 0.06479876]],

       [[0.87643591, 0.15762544, 0.08580714, 0.91867596, 0.41774475],
        [0.31157827, 0.84888892, 0.56376389, 0.62227452, 0.60198114],
        [0.83276231, 0.65303645, 0.11482237, 0.98667223, 0.06543309]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [34]:
# your code/answer here

print(a==e)

# Each element of a has been multiplied by each element of c, which are all ones 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [37]:
# your code here

d_max=d.max()
d_min=d.min()
d_mean=d.mean()
print(d_max, d_min,d_mean)

1.9866722310715672 1.0647987584431002 1.4995354145293878


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [44]:
# your code here

f=np.empty((2,3,5))
print(f)


[[[0.67828832 0.30768576 0.09465794 0.91100142 0.88879985]
  [0.07932956 0.3137879  0.32289145 0.4079848  0.45982861]
  [0.67746761 0.397713   0.73167579 0.59264927 0.06479876]]

 [[0.87643591 0.15762544 0.08580714 0.91867596 0.41774475]
  [0.31157827 0.84888892 0.56376389 0.62227452 0.60198114]
  [0.83276231 0.65303645 0.11482237 0.98667223 0.06543309]]]


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [45]:
# your code here

for i in range(2):
    for j in range(3):
        for q in range(5):
            if d[i,j,q]==d_min:
                f[i,j,q]=0
            elif d_min<d[i,j,q]<d_mean:
                f[i,j,q]=25
            elif d[i,j,q]==d_mean:
                f[i,j,q]=50
            elif d_mean<d[i,j,q]<d_max:
                f[i,j,q]=75
            elif d[i,j,q]==d_max:
                f[i,j,q]=100
f

array([[[ 75.,  25.,  25.,  75.,  75.],
        [ 25.,  25.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,   0.]],

       [[ 75.,  25.,  25.,  75.,  25.],
        [ 25.,  75.,  75.,  75.,  75.],
        [ 75.,  75.,  25., 100.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [46]:
# your code here
print(d)
print(f)

[[[1.67828832 1.30768576 1.09465794 1.91100142 1.88879985]
  [1.07932956 1.3137879  1.32289145 1.4079848  1.45982861]
  [1.67746761 1.397713   1.73167579 1.59264927 1.06479876]]

 [[1.87643591 1.15762544 1.08580714 1.91867596 1.41774475]
  [1.31157827 1.84888892 1.56376389 1.62227452 1.60198114]
  [1.83276231 1.65303645 1.11482237 1.98667223 1.06543309]]]
[[[ 75.  25.  25.  75.  75.]
  [ 25.  25.  25.  25.  25.]
  [ 75.  25.  75.  75.   0.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25.  75.  75.  75.  75.]
  [ 75.  75.  25. 100.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [70]:
# your code here

fs=np.empty((2,3,5),dtype=str)

In [71]:
for i in range(2):
    for j in range(3):
        for q in range(5):
            if f[i][j][q]==0:
                fs[i][j][q]='A'
            elif f[i][j][q]==25:
                fs[i][j][q]='B'
            elif f[i][j][q]==50:
                fs[i][j][q]='C'
            elif f[i][j][q]==75:
                fs[i][j][q]='D'
            elif f[i][j][q]==100:
                fs[i][j][q]='E'

In [73]:
fs

array([[['D', 'B', 'B', 'D', 'D'],
        ['B', 'B', 'B', 'B', 'B'],
        ['D', 'B', 'D', 'D', 'A']],

       [['D', 'B', 'B', 'D', 'B'],
        ['B', 'D', 'D', 'D', 'D'],
        ['D', 'D', 'B', 'E', 'B']]], dtype='<U1')