In [1]:
import numpy as np

In [2]:
# 2 dimensional tensor 

a=np.random.random((2,2))

In [3]:
a

array([[0.46779889, 0.88411548],
       [0.86539784, 0.93761879]])

In [4]:
a[0,0]

0.4677988917234095

In [5]:
a[1,0]

0.8653978377750834

In [6]:
a.round(2)

array([[0.47, 0.88],
       [0.87, 0.94]])

In [7]:
a[0]

array([0.46779889, 0.88411548])

In [8]:
a[:,0]

array([0.46779889, 0.86539784])

In [9]:
# 3 dimensional tensor 

b=np.random.random((4,3,2))

In [10]:
b

array([[[0.08751509, 0.52990609],
        [0.24857782, 0.96455607],
        [0.82134724, 0.65819772]],

       [[0.42918847, 0.79814294],
        [0.27624566, 0.45169912],
        [0.91189569, 0.80497013]],

       [[0.70168817, 0.0400794 ],
        [0.43531947, 0.66134754],
        [0.67953092, 0.21393872]],

       [[0.46445182, 0.08356699],
        [0.62218271, 0.97408588],
        [0.91287758, 0.17269024]]])

In [11]:
# 4 dimensional tensor 

c=np.random.random((5,4,3,2))

In [13]:
b[0]

array([[0.08751509, 0.52990609],
       [0.24857782, 0.96455607],
       [0.82134724, 0.65819772]])

In [14]:
b[:,1]

array([[0.24857782, 0.96455607],
       [0.27624566, 0.45169912],
       [0.43531947, 0.66134754],
       [0.62218271, 0.97408588]])

In [15]:
b[:,:,1]

array([[0.52990609, 0.96455607, 0.65819772],
       [0.79814294, 0.45169912, 0.80497013],
       [0.0400794 , 0.66134754, 0.21393872],
       [0.08356699, 0.97408588, 0.17269024]])

# 2 Lambda functions

In [17]:
square=lambda x: x*x

In [18]:
square(2)

4

In [19]:
div = lambda x,y: x/y if y!=0 else 0

In [21]:
div(5,6)

0.8333333333333334

In [22]:
div(4,0)

0

## create a function that returns a function

In [23]:
def generate_range(lower):
    return lambda upper: range(lower,upper)

In [24]:
custom_range=generate_range(5)

In [25]:
custom_range(10)

range(5, 10)

## Lambda + list comprehension 

In [26]:
[square(i) for i in range(20)]

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361]

In [27]:
topics=['Python','MySQL','Pandas','Web Scraping','Data Viz','Statistics','Machine Learning']

In [29]:
[i.lower().replace(' ','_') for i in topics]

['python',
 'mysql',
 'pandas',
 'web_scraping',
 'data_viz',
 'statistics',
 'machine_learning']

In [28]:
[(lambda x: x.lower().replace(' ','_'))(i) for i in topics]

['python',
 'mysql',
 'pandas',
 'web_scraping',
 'data_viz',
 'statistics',
 'machine_learning']

In [32]:
list(map(lambda x: x.lower().replace(' ','_'),topics))

['python',
 'mysql',
 'pandas',
 'web_scraping',
 'data_viz',
 'statistics',
 'machine_learning']

In [36]:
dct={i:len(i) for i in topics}

In [37]:
import operator 
dict(sorted(dct.items(), key=operator.itemgetter(1),reverse=True))

{'Machine Learning': 16,
 'Web Scraping': 12,
 'Statistics': 10,
 'Data Viz': 8,
 'Python': 6,
 'Pandas': 6,
 'MySQL': 5}

In [38]:
dict(sorted(dct.items(), reverse=True, key=lambda x: x[1]))

{'Machine Learning': 16,
 'Web Scraping': 12,
 'Statistics': 10,
 'Data Viz': 8,
 'Python': 6,
 'Pandas': 6,
 'MySQL': 5}

# 3 Map, Filter, Reduce

## Map 

In [40]:
def func(x):
    return x%2==0

In [41]:
l=[10,23,445,34]

In [42]:
func(l)

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [43]:
[func(i) for i in l]

[True, False, False, True]

In [44]:
list(map(func,l))

[True, False, False, True]

In [45]:
import pandas as pd
import numpy as np

In [46]:
df=pd.DataFrame([[1,2,3],[2,3,np.nan]])

In [47]:
df

0  1    2
0  1  2  3.0
1  2  3  NaN

In [48]:
def ff(x):
    return float(x)

In [49]:
df[0].map(ff)

0    1.0
1    2.0
Name: 0, dtype: float64

**IMPORTANT** `map()` only works with `pd.Series`

In [50]:
df[1].map(lambda x: x**2)

0    4
1    9
Name: 1, dtype: int64

In [51]:
dct={1:'apple',2:'plum'}

In [52]:
df[0].map(dct)

0    apple
1     plum
Name: 0, dtype: object

In [53]:
df[1].map(dct)

0    plum
1     NaN
Name: 1, dtype: object

## Filter

In [55]:
list(map(func,l))

[True, False, False, True]

In [57]:
l

[10, 23, 445, 34]

In [56]:
list(filter(func,l))

[10, 34]

In [58]:
df

0  1    2
0  1  2  3.0
1  2  3  NaN

In [59]:
df.index=['mouse','cat']

In [60]:
df

0  1    2
mouse  1  2  3.0
cat    2  3  NaN

In [61]:
df.filter(like='ouse', axis=0)

0  1    2
mouse  1  2  3.0

In [62]:
df.filter(like='a', axis=0)

0  1   2
cat  2  3 NaN

In [63]:
# Same as : 

df.loc[df.index.str.contains('ouse')]

0  1    2
mouse  1  2  3.0

In [64]:
df.filter(items=[0,2])

0    2
mouse  1  3.0
cat    2  NaN

## Reduce

In [65]:
def func(a,b): return a+b

In [66]:
from functools import reduce

In [67]:
l

[10, 23, 445, 34]

In [68]:
reduce(func,l)

512

In [69]:
sum(l)

512

In [70]:
def func(a,b):
    return a if a>b else b

In [71]:
reduce(func,l)

445

# 4 MAAM - Map, Apply, ApplyMap

In [73]:
df=pd.read_csv('https://ironhack.school/asset-v1:IRONHACK+DAFT+201910_PAR+type@asset+block@IMDB-Movie-Data.csv')

In [74]:
df

Rank                    Title                     Genre  \
0       1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1       2               Prometheus  Adventure,Mystery,Sci-Fi   
2       3                    Split           Horror,Thriller   
3       4                     Sing   Animation,Comedy,Family   
4       5            Suicide Squad  Action,Adventure,Fantasy   
..    ...                      ...                       ...   
995   996     Secret in Their Eyes       Crime,Drama,Mystery   
996   997          Hostel: Part II                    Horror   
997   998   Step Up 2: The Streets       Drama,Music,Romance   
998   999             Search Party          Adventure,Comedy   
999  1000               Nine Lives     Comedy,Family,Fantasy   

                                           Description              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn   
1    Following clues to the origin of mankind, a te...          Ridley Scott   
2    Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3    In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4    A secret government agency recruits some of th...            David Ayer   
..                                                 ...                   ...   
995  A tight-knit team of rising investigators, alo...             Billy Ray   
996  Three American college students studying abroa...              Eli Roth   
997  Romantic sparks occur between two dance studen...            Jon M. Chu   
998  A pair of friends embark on a mission to reuni...        Scot Armstrong   
999  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld   

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012   
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016   
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016   
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016   
..                                                 ...   ...   
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015   
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007   
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008   
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014   
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016   

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  
0                  121     8.1  757074              333.13       76.0  
1                  124     7.0  485820              126.46       65.0  
2                  117     7.3  157606              138.12       62.0  
3                  108     7.2   60545              270.32       59.0  
4                  123     6.2  393727              325.02       40.0  
..                 ...     ...     ...                 ...        ...  
995                111     6.2   27585                 NaN       45.0  
996                 94     5.5   73152               17.54       46.0  
997                 98     6.2   70699               58.01       50.0  
998                 93     5.6    4881                 NaN       22.0  
999                 87     5.3   12435               19.64       11.0  

[1000 rows x 12 columns]

In [75]:
df.Rating.max()

9.0

In [76]:
df.Rating.min()

1.9

In [77]:
df.Rating/2

0      4.05
1      3.50
2      3.65
3      3.60
4      3.10
       ... 
995    3.10
996    2.75
997    3.10
998    2.80
999    2.65
Name: Rating, Length: 1000, dtype: float64

In [78]:
df.Rating.map(lambda x: x/2)

0      4.05
1      3.50
2      3.65
3      3.60
4      3.10
       ... 
995    3.10
996    2.75
997    3.10
998    2.80
999    2.65
Name: Rating, Length: 1000, dtype: float64

In [79]:
def column_range(x):
    return x.max()-x.min()

In [80]:
df.Rating.map(column_range)

AttributeError: 'float' object has no attribute 'max'

In [81]:
df[['Rating']].apply(column_range)

Rating    7.1
dtype: float64

In [84]:
df[['Rating','Runtime (Minutes)']].apply(column_range)

Rating                 7.1
Runtime (Minutes)    125.0
dtype: float64

In [89]:
def column_range(x):
    return x.max()-x.min() if type(x[0]) in (int,float) else len(x)

In [90]:
df.apply(column_range)

Rank                  1000
Title                 1000
Genre                 1000
Description           1000
Director              1000
Actors                1000
Year                  1000
Runtime (Minutes)     1000
Rating                1000
Votes                 1000
Revenue (Millions)    1000
Metascore             1000
dtype: int64

# All above + lambda

In [92]:
df[df.Genre.str.lower().str.contains('action')].head()

Rank                    Title                       Genre  \
0      1  Guardians of the Galaxy     Action,Adventure,Sci-Fi   
4      5            Suicide Squad    Action,Adventure,Fantasy   
5      6           The Great Wall    Action,Adventure,Fantasy   
8      9       The Lost City of Z  Action,Adventure,Biography   
12    13                Rogue One     Action,Adventure,Sci-Fi   

                                          Description        Director  \
0   A group of intergalactic criminals are forced ...      James Gunn   
4   A secret government agency recruits some of th...      David Ayer   
5   European mercenaries searching for black powde...     Yimou Zhang   
8   A true-life drama, centering on British explor...      James Gray   
12  The Rebel Alliance makes a risky move to steal...  Gareth Edwards   

                                               Actors  Year  \
0   Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
4   Will Smith, Jared Leto, Margot Robbie, Viola D...  2016   
5       Matt Damon, Tian Jing, Willem Dafoe, Andy Lau  2016   
8   Charlie Hunnam, Robert Pattinson, Sienna Mille...  2016   
12  Felicity Jones, Diego Luna, Alan Tudyk, Donnie...  2016   

    Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  
0                 121     8.1  757074              333.13       76.0  
4                 123     6.2  393727              325.02       40.0  
5                 103     6.1   56036               45.13       42.0  
8                 141     7.1    7188                8.01       78.0  
12                133     7.9  323118              532.17       65.0

In [93]:
df[(df.Genre.str.lower().str.contains('action'))&(~df.Genre.str.lower().str.contains('fantasy'))]

Rank                     Title                       Genre  \
0       1   Guardians of the Galaxy     Action,Adventure,Sci-Fi   
8       9        The Lost City of Z  Action,Adventure,Biography   
12     13                 Rogue One     Action,Adventure,Sci-Fi   
14     15                  Colossal         Action,Comedy,Drama   
17     18              Jason Bourne             Action,Thriller   
..    ...                       ...                         ...   
954   955                Death Race      Action,Sci-Fi,Thriller   
958   959            3 Days to Kill       Action,Drama,Thriller   
968   969                   Wrecker      Action,Horror,Thriller   
969   970           The Lone Ranger    Action,Adventure,Western   
993   994  Resident Evil: Afterlife     Action,Adventure,Horror   

                                           Description            Director  \
0    A group of intergalactic criminals are forced ...          James Gunn   
8    A true-life drama, centering on British explor...          James Gray   
12   The Rebel Alliance makes a risky move to steal...      Gareth Edwards   
14   Gloria is an out-of-work party girl forced to ...     Nacho Vigalondo   
17   The CIA's most dangerous former operative is d...     Paul Greengrass   
..                                                 ...                 ...   
954  Ex-con Jensen Ames is forced by the warden of ...  Paul W.S. Anderson   
958  A dying CIA agent trying to reconnect with his...                 McG   
968  Best friends Emily and Lesley go on a road tri...      Micheal Bafaro   
969  Native American warrior Tonto recounts the unt...      Gore Verbinski   
993  While still out to destroy the evil Umbrella C...  Paul W.S. Anderson   

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
8    Charlie Hunnam, Robert Pattinson, Sienna Mille...  2016   
12   Felicity Jones, Diego Luna, Alan Tudyk, Donnie...  2016   
14   Anne Hathaway, Jason Sudeikis, Austin Stowell,...  2016   
17   Matt Damon, Tommy Lee Jones, Alicia Vikander,V...  2016   
..                                                 ...   ...   
954  Jason Statham, Joan Allen, Tyrese Gibson, Ian ...  2008   
958  Kevin Costner, Hailee Steinfeld, Connie Nielse...  2014   
968  Anna Hutchison, Andrea Whitburn, Jennifer Koen...  2015   
969  Johnny Depp, Armie Hammer, William Fichtner,To...  2013   
993  Milla Jovovich, Ali Larter, Wentworth Miller,K...  2010   

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  
0                  121     8.1  757074              333.13       76.0  
8                  141     7.1    7188                8.01       78.0  
12                 133     7.9  323118              532.17       65.0  
14                 109     6.4    8612                2.87       70.0  
17                 123     6.7  150823              162.16       58.0  
..                 ...     ...     ...                 ...        ...  
954                105     6.4  173731               36.06       43.0  
958                117     6.2   73567               30.69       40.0  
968                 83     3.5    1210                 NaN       37.0  
969                150     6.5  190855               89.29        NaN  
993                 97     5.9  140900               60.13       37.0  

[263 rows x 12 columns]

In [ ]:
df[df.Genre.str.split(',').map(lambda x: len(x)<3)] # 2 genres max
df[df.Genre.str.lower().str.contains('action')] # contains action

In [96]:
df[df.Genre.str.lower().str.split(',').map(lambda x: (set(x)-set(['action','thriller','adventure']))==set())] # only contains action, thriller and adventure

Rank                                          Title  \
17     18                                   Jason Bourne   
123   124                           Boyka: Undisputed IV   
124   125                          The Dark Knight Rises   
164   165                                  Casino Royale   
169   170                                        Spectre   
233   234             Mission: Impossible - Rogue Nation   
270   271                                        Skyfall   
282   283                                    Death Proof   
284   285                                       Hercules   
289   290                                           Iris   
344   345                                   Spider-Man 3   
368   369                         The Amazing Spider-Man   
379   380                              The Expendables 3   
410   411                                          Taken   
433   434           Mission: Impossible - Ghost Protocol   
444   445                                   The Thinning   
453   454                             Olympus Has Fallen   
560   561                                The Expendables   
580   581                           Kickboxer: Vengeance   
624   625                                        Taken 3   
698   699                          Live Free or Die Hard   
729   730                                      The Guest   
746   747                             Only for One Night   
770   771                              Quantum of Solace   
777   778                                     Final Girl   
844   845                                    Unstoppable   
848   849                                    Mean Dreams   
869   870                        Mission: Impossible III   
872   873                                       Red Dawn   
911   912  I Am the Pretty Thing That Lives in the House   
916   917                              The Expendables 2   
923   924                                      No Escape   
933   934                                         Detour   
942   943                                     Transpecos   
949   950                                          Kicks   

                         Genre  \
17             Action,Thriller   
123                     Action   
124            Action,Thriller   
164  Action,Adventure,Thriller   
169  Action,Adventure,Thriller   
233  Action,Adventure,Thriller   
270  Action,Adventure,Thriller   
282                   Thriller   
284           Action,Adventure   
289                   Thriller   
344           Action,Adventure   
368           Action,Adventure   
379  Action,Adventure,Thriller   
410            Action,Thriller   
433  Action,Adventure,Thriller   
444                   Thriller   
453            Action,Thriller   
560  Action,Adventure,Thriller   
580                     Action   
624            Action,Thriller   
698  Action,Adventure,Thriller   
729                   Thriller   
746                   Thriller   
770  Action,Adventure,Thriller   
777            Action,Thriller   
844            Action,Thriller   
848                   Thriller   
869  Action,Adventure,Thriller   
872            Action,Thriller   
911                   Thriller   
916  Action,Adventure,Thriller   
923            Action,Thriller   
933                   Thriller   
942                   Thriller   
949                  Adventure   

                                           Description               Director  \
17   The CIA's most dangerous former operative is d...        Paul Greengrass   
123  In the fourth installment of the fighting fran...        Todor Chapkanov   
124  Eight years after the Joker's reign of anarchy...      Christopher Nolan   
164  Armed with a licence to kill, Secret Agent Jam...        Martin Campbell   
169  A cryptic message from Bond's past sends him o...             Sam Mendes   
233  Ethan and team take on their most impossible m...  Christopher McQuarrie   
270  Bond's loyalty to M is tested when her past co.

In [100]:
df[df.Genre.str.lower().str.split(',').map(lambda x: 
                                           (len(x)<3) & 
                                           ('action' in x)&
                                           ((set(x) - set(['action','thriller','adventure']))==set()))]

Rank                   Title             Genre  \
17     18            Jason Bourne   Action,Thriller   
123   124    Boyka: Undisputed IV            Action   
124   125   The Dark Knight Rises   Action,Thriller   
284   285                Hercules  Action,Adventure   
344   345            Spider-Man 3  Action,Adventure   
368   369  The Amazing Spider-Man  Action,Adventure   
410   411                   Taken   Action,Thriller   
453   454      Olympus Has Fallen   Action,Thriller   
580   581    Kickboxer: Vengeance            Action   
624   625                 Taken 3   Action,Thriller   
777   778              Final Girl   Action,Thriller   
844   845             Unstoppable   Action,Thriller   
872   873                Red Dawn   Action,Thriller   
923   924               No Escape   Action,Thriller   

                                           Description           Director  \
17   The CIA's most dangerous former operative is d...    Paul Greengrass   
123  In the fourth installment of the fighting fran...    Todor Chapkanov   
124  Eight years after the Joker's reign of anarchy...  Christopher Nolan   
284  Having endured his legendary twelve labors, He...       Brett Ratner   
344  A strange black entity from another world bond...          Sam Raimi   
368  After Peter Parker is bitten by a genetically ...          Marc Webb   
410  A retired CIA agent travels across Europe and ...       Pierre Morel   
453  Disgraced Secret Service agent (and former pre...      Antoine Fuqua   
580         A kick boxer is out to avenge his brother.     John Stockwell   
624  Ex-government operative Bryan Mills is accused...    Olivier Megaton   
777  A man teaches a young woman how to become a co...      Tyler Shields   
844  With an unmanned, half-mile-long freight train...         Tony Scott   
872  A group of teenagers look to save their town f...        Dan Bradley   
923  In their new overseas home, an American family...  John Erick Dowdle   

                                                Actors  Year  \
17   Matt Damon, Tommy Lee Jones, Alicia Vikander,V...  2016   
123  Scott Adkins, Teodora Duhovnikova, Alon Aboutb...  2016   
124  Christian Bale, Tom Hardy, Anne Hathaway,Gary ...  2012   
284  Dwayne Johnson, John Hurt, Ian McShane, Joseph...  2014   
344  Tobey Maguire, Kirsten Dunst, Topher Grace, Th...  2007   
368  Andrew Garfield, Emma Stone, Rhys Ifans, Irrfa...  2012   
410  Liam Neeson, Maggie Grace, Famke Janssen, Lela...  2008   
453  Gerard Butler, Aaron Eckhart, Morgan Freeman,A...  2013   
580  Dave Bautista, Alain Moussi, Gina Carano, Jean...  2016   
624  Liam Neeson, Forest Whitaker, Maggie Grace,Fam...  2014   
777  Abigail Breslin, Wes Bentley, Logan Huffman,Al...  2015   
844  Denzel Washington, Chris Pine, Rosario Dawson,...  2010   
872  Chris Hemsworth, Isabel Lucas, Josh Hutcherson...  2012   
923  Lake Bell, Pierce Brosnan, Owen Wilson,Chatcha...  2015   

     Runtime (Minutes)  Rating    Votes  Revenue (Millions)  Metascore  
17                 123     6.7   150823              162.16       58.0  
123                 86     7.4    10428                 NaN        NaN  
124                164     8.5  1222645              448.13       78.0  
284                 98     6.0   122838               72.66       47.0  
344                139     6.2   406219              336.53       59.0  
368                136     7.0   474320              262.03       66.0  
410                 93     7.8   502961              145.00       50.0  
453                119     6.5   214994               98.90       41.0  
580                 90     4.9     6809              131.56       37.0  
624                109     6.0   144715               89.25       26.0  
777                 90     4.7     9026                 NaN       56.0  
844                 98     6.8   157499               81.56       69.0  
872                 93     5.4    64584               44.80       31.0  
923                103     6.8    57921 

## Applymap

In [101]:
df_d=df[['Title','Description']]

In [102]:
df_d.Description.str.split().map(len).mean()

27.921

In [103]:
df_d.Title.str.split().map(len).mean()

2.605

In [104]:
df_d.applymap(lambda x: len(x.split())).mean()

Title           2.605
Description    27.921
dtype: float64