In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
%matplotlib inline

# Get data

In [2]:
df=pd.read_csv('/Users/etienneleconte/Downloads/telecom_churn (1).csv')

In [3]:
df.head()

State  Account length  Area code International plan Voice mail plan  \
0    KS             128        415                 No             Yes   
1    OH             107        415                 No             Yes   
2    NJ             137        415                 No              No   
3    OH              84        408                Yes              No   
4    OK              75        415                Yes              No   

   Number vmail messages  Total day minutes  Total day calls  \
0                     25              265.1              110   
1                     26              161.6              123   
2                      0              243.4              114   
3                      0              299.4               71   
4                      0              166.7              113   

   Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0             45.07              197.4               99             16.78   
1             27.47              195.5              103             16.62   
2             41.38              121.2              110             10.30   
3             50.90               61.9               88              5.26   
4             28.34              148.3              122             12.61   

   Total night minutes  Total night calls  Total night charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   Total intl minutes  Total intl calls  Total intl charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   Customer service calls  Churn  
0                       1  False  
1                       1  False  
2                       0  False  
3                       2  False  
4                       3  False

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   State                   3333 non-null   object 
 1   Account length          3333 non-null   int64  
 2   Area code               3333 non-null   int64  
 3   International plan      3333 non-null   object 
 4   Voice mail plan         3333 non-null   object 
 5   Number vmail messages   3333 non-null   int64  
 6   Total day minutes       3333 non-null   float64
 7   Total day calls         3333 non-null   int64  
 8   Total day charge        3333 non-null   float64
 9   Total eve minutes       3333 non-null   float64
 10  Total eve calls         3333 non-null   int64  
 11  Total eve charge        3333 non-null   float64
 12  Total night minutes     3333 non-null   float64
 13  Total night calls       3333 non-null   int64  
 14  Total night charge      3333 non-null   

In [5]:
df['International plan']=df['International plan'].map({'Yes':True,'No':False})
df['Voice mail plan']=df['Voice mail plan'].map({'Yes':True,'No':False})

In [6]:
df.head()

State  Account length  Area code  International plan  Voice mail plan  \
0    KS             128        415               False             True   
1    OH             107        415               False             True   
2    NJ             137        415               False            False   
3    OH              84        408                True            False   
4    OK              75        415                True            False   

   Number vmail messages  Total day minutes  Total day calls  \
0                     25              265.1              110   
1                     26              161.6              123   
2                      0              243.4              114   
3                      0              299.4               71   
4                      0              166.7              113   

   Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0             45.07              197.4               99             16.78   
1             27.47              195.5              103             16.62   
2             41.38              121.2              110             10.30   
3             50.90               61.9               88              5.26   
4             28.34              148.3              122             12.61   

   Total night minutes  Total night calls  Total night charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   Total intl minutes  Total intl calls  Total intl charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   Customer service calls  Churn  
0                       1  False  
1                       1  False  
2                       0  False  
3                       2  False  
4                       3  False

In [7]:
df.drop('State',axis=1,inplace=True)

In [8]:
 df.Churn.value_counts(normalize=True)

False    0.855086
True     0.144914
Name: Churn, dtype: float64

# Assumptions

Assume that the dataset has no outliers, errors or whatsoever. Assume that the distribution is fine and that we don't need to transform our variables

In [9]:
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, f1_score, precision_score

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [10]:
#pip install xgboost

In [20]:
pip install catboost

Note: you may need to restart the kernel to use updated packages.


In [22]:
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

In [13]:
X_train, X_test,y_train,y_test = train_test_split(df.drop('Churn',axis=1), \
                                                  df.Churn, \
                                                  test_size=1/3, \
                                                  random_state=42, \
                                                  stratify=df.Churn)

## Decision tree 

In [24]:
model1=DecisionTreeClassifier()
model1.fit(X_train, y_train)
y_pred1=model1.predict(X_test)
conf1=confusion_matrix(y_test, y_pred1)
acc1=accuracy_score(y_test, y_pred1)
rec1=recall_score(y_test, y_pred1)
pre1=precision_score(y_test, y_pred1)
f11=f1_score(y_test, y_pred1)
display(conf1)
print('Accuracy', acc1)
print('Recall', rec1)
print('Precision', pre1)
print('F1', f11)

array([[900,  50],
       [ 56, 105]])

Accuracy 0.9045904590459046
Recall 0.6521739130434783
Precision 0.6774193548387096
F1 0.6645569620253163


## Random Forest

In [23]:
model1=RandomForestClassifier()
model1.fit(X_train, y_train)
y_pred1=model1.predict(X_test)
conf1=confusion_matrix(y_test, y_pred1)
acc1=accuracy_score(y_test, y_pred1)
rec1=recall_score(y_test, y_pred1)
pre1=precision_score(y_test, y_pred1)
f11=f1_score(y_test, y_pred1)
display(conf1)
print('Accuracy', acc1)
print('Recall', rec1)
print('Precision', pre1)
print('F1', f11)

array([[940,  10],
       [ 46, 115]])

Accuracy 0.9495949594959496
Recall 0.7142857142857143
Precision 0.92
F1 0.8041958041958042


## Random Forest balanced

In [26]:
model1=RandomForestClassifier(class_weight='balanced')
model1.fit(X_train, y_train)
y_pred1=model1.predict(X_test)
conf1=confusion_matrix(y_test, y_pred1)
acc1=accuracy_score(y_test, y_pred1)
rec1=recall_score(y_test, y_pred1)
pre1=precision_score(y_test, y_pred1)
f11=f1_score(y_test, y_pred1)
display(conf1)
print('Accuracy', acc1)
print('Recall', rec1)
print('Precision', pre1)
print('F1', f11)

array([[938,  12],
       [ 53, 108]])

Accuracy 0.9414941494149415
Recall 0.6708074534161491
Precision 0.9
F1 0.7686832740213524


## XGBoost

In [28]:
model1=XGBClassifier()
model1.fit(X_train, y_train)
y_pred1=model1.predict(X_test)
conf1=confusion_matrix(y_test, y_pred1)
acc1=accuracy_score(y_test, y_pred1)
rec1=recall_score(y_test, y_pred1)
pre1=precision_score(y_test, y_pred1)
f11=f1_score(y_test, y_pred1)
display(conf1)
print('Accuracy', acc1)
print('Recall', rec1)
print('Precision', pre1)
print('F1', f11)

array([[932,  18],
       [ 44, 117]])

Accuracy 0.9441944194419442
Recall 0.7267080745341615
Precision 0.8666666666666667
F1 0.7905405405405406


## AdaBoost

In [29]:
model1=AdaBoostClassifier()
model1.fit(X_train, y_train)
y_pred1=model1.predict(X_test)
conf1=confusion_matrix(y_test, y_pred1)
acc1=accuracy_score(y_test, y_pred1)
rec1=recall_score(y_test, y_pred1)
pre1=precision_score(y_test, y_pred1)
f11=f1_score(y_test, y_pred1)
display(conf1)
print('Accuracy', acc1)
print('Recall', rec1)
print('Precision', pre1)
print('F1', f11)

array([[906,  44],
       [102,  59]])

Accuracy 0.8685868586858686
Recall 0.36645962732919257
Precision 0.5728155339805825
F1 0.446969696969697


## CatBoost

In [33]:
model1=CatBoostClassifier()
model1.fit(X_train, y_train)
y_pred1=model1.predict(X_test)
conf1=confusion_matrix(y_test, [eval(str(i)) for i in y_pred1])
acc1=accuracy_score(y_test, [eval(str(i)) for i in y_pred1])
rec1=recall_score(y_test, [eval(str(i)) for i in y_pred1])
pre1=precision_score(y_test, [eval(str(i)) for i in y_pred1])
f11=f1_score(y_test, [eval(str(i)) for i in y_pred1])
display(conf1)
print('Accuracy', acc1)
print('Recall', rec1)
print('Precision', pre1)
print('F1', f11)

Learning rate set to 0.014488
0:	learn: 0.6810795	total: 11ms	remaining: 11s
1:	learn: 0.6671237	total: 15.9ms	remaining: 7.93s
2:	learn: 0.6547928	total: 20.3ms	remaining: 6.76s
3:	learn: 0.6388798	total: 24.2ms	remaining: 6.02s
4:	learn: 0.6255185	total: 28.3ms	remaining: 5.63s
5:	learn: 0.6107657	total: 32.1ms	remaining: 5.32s
6:	learn: 0.5977423	total: 36.4ms	remaining: 5.16s
7:	learn: 0.5868114	total: 40.4ms	remaining: 5.01s
8:	learn: 0.5773122	total: 44.8ms	remaining: 4.94s
9:	learn: 0.5651216	total: 48.8ms	remaining: 4.83s
10:	learn: 0.5549107	total: 52.7ms	remaining: 4.73s
11:	learn: 0.5451468	total: 57.1ms	remaining: 4.7s
12:	learn: 0.5351335	total: 61.4ms	remaining: 4.66s
13:	learn: 0.5260024	total: 65.6ms	remaining: 4.62s
14:	learn: 0.5170633	total: 69.4ms	remaining: 4.56s
15:	learn: 0.5050288	total: 73.4ms	remaining: 4.51s
16:	learn: 0.4965513	total: 77.5ms	remaining: 4.48s
17:	learn: 0.4896704	total: 81.5ms	remaining: 4.45s
18:	learn: 0.4817171	total: 85.3ms	remaining: 4.4

196:	learn: 0.1590735	total: 941ms	remaining: 3.83s
197:	learn: 0.1587056	total: 944ms	remaining: 3.82s
198:	learn: 0.1582498	total: 949ms	remaining: 3.82s
199:	learn: 0.1578536	total: 956ms	remaining: 3.82s
200:	learn: 0.1574222	total: 962ms	remaining: 3.83s
201:	learn: 0.1571682	total: 969ms	remaining: 3.83s
202:	learn: 0.1568094	total: 974ms	remaining: 3.83s
203:	learn: 0.1566142	total: 979ms	remaining: 3.82s
204:	learn: 0.1563262	total: 983ms	remaining: 3.81s
205:	learn: 0.1558397	total: 988ms	remaining: 3.81s
206:	learn: 0.1555011	total: 991ms	remaining: 3.8s
207:	learn: 0.1552833	total: 995ms	remaining: 3.79s
208:	learn: 0.1549851	total: 1000ms	remaining: 3.78s
209:	learn: 0.1547133	total: 1s	remaining: 3.77s
210:	learn: 0.1543980	total: 1.01s	remaining: 3.77s
211:	learn: 0.1541448	total: 1.01s	remaining: 3.76s
212:	learn: 0.1538665	total: 1.01s	remaining: 3.75s
213:	learn: 0.1535546	total: 1.02s	remaining: 3.74s
214:	learn: 0.1533492	total: 1.02s	remaining: 3.74s
215:	learn: 0.1

387:	learn: 0.1206149	total: 1.9s	remaining: 2.99s
388:	learn: 0.1204678	total: 1.9s	remaining: 2.99s
389:	learn: 0.1203510	total: 1.91s	remaining: 2.98s
390:	learn: 0.1201750	total: 1.91s	remaining: 2.98s
391:	learn: 0.1199383	total: 1.92s	remaining: 2.98s
392:	learn: 0.1198300	total: 1.92s	remaining: 2.97s
393:	learn: 0.1197171	total: 1.93s	remaining: 2.96s
394:	learn: 0.1195838	total: 1.93s	remaining: 2.96s
395:	learn: 0.1194457	total: 1.94s	remaining: 2.95s
396:	learn: 0.1193382	total: 1.94s	remaining: 2.95s
397:	learn: 0.1191906	total: 1.94s	remaining: 2.94s
398:	learn: 0.1190848	total: 1.95s	remaining: 2.94s
399:	learn: 0.1189265	total: 1.95s	remaining: 2.93s
400:	learn: 0.1188129	total: 1.96s	remaining: 2.92s
401:	learn: 0.1187281	total: 1.96s	remaining: 2.92s
402:	learn: 0.1186710	total: 1.97s	remaining: 2.91s
403:	learn: 0.1185147	total: 1.97s	remaining: 2.9s
404:	learn: 0.1183338	total: 1.97s	remaining: 2.9s
405:	learn: 0.1182403	total: 1.98s	remaining: 2.89s
406:	learn: 0.11

565:	learn: 0.1002323	total: 2.65s	remaining: 2.04s
566:	learn: 0.1001593	total: 2.66s	remaining: 2.03s
567:	learn: 0.0999971	total: 2.67s	remaining: 2.03s
568:	learn: 0.0999073	total: 2.67s	remaining: 2.03s
569:	learn: 0.0998931	total: 2.68s	remaining: 2.02s
570:	learn: 0.0997890	total: 2.68s	remaining: 2.02s
571:	learn: 0.0996787	total: 2.69s	remaining: 2.01s
572:	learn: 0.0995455	total: 2.69s	remaining: 2.01s
573:	learn: 0.0994560	total: 2.7s	remaining: 2s
574:	learn: 0.0994232	total: 2.7s	remaining: 2s
575:	learn: 0.0993488	total: 2.71s	remaining: 1.99s
576:	learn: 0.0993183	total: 2.71s	remaining: 1.99s
577:	learn: 0.0992538	total: 2.71s	remaining: 1.98s
578:	learn: 0.0991994	total: 2.72s	remaining: 1.98s
579:	learn: 0.0990546	total: 2.72s	remaining: 1.97s
580:	learn: 0.0989605	total: 2.73s	remaining: 1.97s
581:	learn: 0.0989317	total: 2.73s	remaining: 1.96s
582:	learn: 0.0987782	total: 2.73s	remaining: 1.96s
583:	learn: 0.0987449	total: 2.74s	remaining: 1.95s
584:	learn: 0.098637

743:	learn: 0.0844630	total: 3.41s	remaining: 1.17s
744:	learn: 0.0843916	total: 3.42s	remaining: 1.17s
745:	learn: 0.0843134	total: 3.42s	remaining: 1.17s
746:	learn: 0.0841783	total: 3.43s	remaining: 1.16s
747:	learn: 0.0841329	total: 3.43s	remaining: 1.16s
748:	learn: 0.0840807	total: 3.44s	remaining: 1.15s
749:	learn: 0.0840274	total: 3.45s	remaining: 1.15s
750:	learn: 0.0839760	total: 3.45s	remaining: 1.14s
751:	learn: 0.0838734	total: 3.46s	remaining: 1.14s
752:	learn: 0.0837363	total: 3.46s	remaining: 1.13s
753:	learn: 0.0836682	total: 3.46s	remaining: 1.13s
754:	learn: 0.0836119	total: 3.47s	remaining: 1.13s
755:	learn: 0.0835093	total: 3.47s	remaining: 1.12s
756:	learn: 0.0833834	total: 3.48s	remaining: 1.11s
757:	learn: 0.0832826	total: 3.48s	remaining: 1.11s
758:	learn: 0.0831467	total: 3.48s	remaining: 1.11s
759:	learn: 0.0831075	total: 3.49s	remaining: 1.1s
760:	learn: 0.0829853	total: 3.49s	remaining: 1.1s
761:	learn: 0.0828593	total: 3.5s	remaining: 1.09s
762:	learn: 0.0

932:	learn: 0.0685432	total: 4.38s	remaining: 314ms
933:	learn: 0.0685079	total: 4.38s	remaining: 310ms
934:	learn: 0.0684147	total: 4.39s	remaining: 305ms
935:	learn: 0.0683175	total: 4.4s	remaining: 301ms
936:	learn: 0.0682868	total: 4.4s	remaining: 296ms
937:	learn: 0.0682755	total: 4.41s	remaining: 291ms
938:	learn: 0.0681954	total: 4.41s	remaining: 287ms
939:	learn: 0.0681542	total: 4.42s	remaining: 282ms
940:	learn: 0.0680609	total: 4.42s	remaining: 277ms
941:	learn: 0.0679544	total: 4.43s	remaining: 273ms
942:	learn: 0.0678718	total: 4.43s	remaining: 268ms
943:	learn: 0.0678048	total: 4.43s	remaining: 263ms
944:	learn: 0.0677179	total: 4.44s	remaining: 258ms
945:	learn: 0.0676567	total: 4.44s	remaining: 254ms
946:	learn: 0.0676482	total: 4.45s	remaining: 249ms
947:	learn: 0.0675887	total: 4.45s	remaining: 244ms
948:	learn: 0.0674931	total: 4.46s	remaining: 239ms
949:	learn: 0.0674391	total: 4.46s	remaining: 235ms
950:	learn: 0.0672993	total: 4.46s	remaining: 230ms
951:	learn: 0.

array([[940,  10],
       [ 39, 122]])

Accuracy 0.9558955895589559
Recall 0.7577639751552795
Precision 0.9242424242424242
F1 0.8327645051194539


In [ ]:
## 

In [ ]:
model1=AdaBoostClassifier()
model1.fit(X_train, y_train)
y_pred1=model1.predict(X_test)
conf1=confusion_matrix(y_test, y_pred1)
acc1=accuracy_score(y_test, y_pred1)
rec1=recall_score(y_test, y_pred1)
pre1=precision_score(y_test, y_pred1)
f11=f1_score(y_test, y_pred1)
display(conf1)
print('Accuracy', acc1)
print('Recall', rec1)
print('Precision', pre1)
print('F1', f11)